version: 2
jobs:
  build:
    docker:
      - image: contribu/buildenv_docker
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run: mkdir -p /tmp/results
#      - run:
#          name: install java and swagger-codegen
#          command: |
#            apt-get update
#            apt-get install -y software-properties-common
#            add-apt-repository ppa:webupd8team/java
#            apt-get update
#            echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
#            apt-get install -y oracle-java8-installer oracle-java8-set-default
#            wget http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.3.1/swagger-codegen-cli-2.3.1.jar -O /tmp/swagger-codegen-cli.jar
#      - run:
#          name: install custom template
#          command: |
#            git clone -b feature/aimastering git@github.com:contribu/swagger-codegen.git /tmp/swagger-codegen
      - run:
          name: generate clients
          command: |
            ruby scripts/generate.rb
      - store_artifacts:
          path: /tmp/results
          destination: results
      - deploy:
          name: push clients
          command: |
            ruby scripts/push.rb
workflows:
  version: 2
  normal_workflow:
    jobs:
    - build
  schedule_workflow:
    triggers:
    - schedule:
        cron: "12 5 * * *"
        filters:
          branches:
            only:
            - master
    jobs:
    - build
