version: 2
jobs:
  build:
    docker:
      - image: contribu/buildenv_docker
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: generate clients
          command: |
            ruby .circleci/generate.rb
      - store_artifacts:
          path: /tmp/results
          destination: results
      - deploy:
          name: push clients
          command: |
            ruby .circleci/push.rb
