version: 2
jobs:
  build:
    docker:
      - image: contribu/buildenv_docker
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install java and swagger-codegen
          command: |
            apt-get update
            apt-get install -y software-properties-common
            add-apt-repository ppa:webupd8team/java
            apt-get update
            echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
            apt-get install -y oracle-java8-installer
            apt-get install -y oracle-java8-set-default
            wget http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.3.1/swagger-codegen-cli-2.3.1.jar -O /tmp/swagger-codegen-cli.jar
      - run:
          name: generate ruby client
          command: |
            git clone git@github.com:ai-mastering/aimastering-ruby.git /tmp/output/aimastering-ruby
            rm -rf /tmp/output/aimastering-ruby/*

            java -jar /tmp/swagger-codegen-cli.jar generate \
              -i output/api_spec.json \
              -l ruby \
              --additional-properties gemName=aimastering \
              --additional-properties gemAuthor='AI Mastering' \
              --additional-properties gemHomepage='https://github.com/ai-mastering/aimastering-ruby' \
              --additional-properties gemLicense=MIT \
              -o /tmp/output/aimastering-ruby

            cd /tmp/output/aimastering-ruby
            gem build aimastering.gemspec
            git add .
            git commit -m "Generated by circleci"
      - store_artifacts:
          path: /tmp/output
          destination: output
      - deploy:
          name: push to repository
          command: |
            (cd /tmp/output/aimastering-ruby && git push origin master)
